include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_function_literals_in_foreach_calls: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  trailing_commas: preserve
